import { TabTheme } from "./types";
// Modern gradient tab themes for visual distinction
export const tabThemes: TabTheme[] = [
  {
    gradient: "from-purple-500 to-indigo-500",
    bg: "bg-gradient-to-r from-purple-50 to-indigo-50",
    border: "border-purple-200",
    text: "text-purple-900",
    ring: "ring-purple-300",
    hover: "hover:from-purple-100 hover:to-indigo-100",
  },
  {
    gradient: "from-blue-500 to-cyan-500",
    bg: "bg-gradient-to-r from-blue-50 to-cyan-50",
    border: "border-blue-200",
    text: "text-blue-700",
    ring: "ring-blue-300",
    hover: "hover:from-blue-100 hover:to-cyan-100",
  },
  {
    gradient: "from-emerald-500 to-teal-500",
    bg: "bg-gradient-to-r from-emerald-50 to-teal-50",
    border: "border-emerald-200",
    text: "text-emerald-700",
    ring: "ring-emerald-300",
    hover: "hover:from-emerald-100 hover:to-teal-100",
  },
  {
    gradient: "from-amber-500 to-orange-500",
    bg: "bg-gradient-to-r from-amber-50 to-orange-50",
    border: "border-amber-200",
    text: "text-amber-700",
    ring: "ring-amber-300",
    hover: "hover:from-amber-100 hover:to-orange-100",
  },
  {
    gradient: "from-purple-500 to-violet-500",
    bg: "bg-gradient-to-r from-purple-50 to-violet-50",
    border: "border-purple-200",
    text: "text-purple-700",
    ring: "ring-purple-300",
    hover: "hover:from-purple-100 hover:to-violet-100",
  },
  {
    gradient: "from-sky-500 to-blue-500",
    bg: "bg-gradient-to-r from-sky-50 to-blue-50",
    border: "border-sky-200",
    text: "text-sky-700",
    ring: "ring-sky-300",
    hover: "hover:from-sky-100 hover:to-blue-100",
  },
  {
    gradient: "from-indigo-500 to-purple-500",
    bg: "bg-gradient-to-r from-indigo-50 to-purple-50",
    border: "border-indigo-200",
    text: "text-indigo-700",
    ring: "ring-indigo-300",
    hover: "hover:from-indigo-100 hover:to-purple-100",
  },
  {
    gradient: "from-blue-500 to-slate-500",
    bg: "bg-gradient-to-r from-blue-50 to-slate-50",
    border: "border-blue-200",
    text: "text-blue-700",
    ring: "ring-blue-300",
    hover: "hover:from-blue-100 hover:to-slate-100",
  },
  // New themes
  {
    gradient: "from-slate-500 to-gray-500",
    bg: "bg-gradient-to-r from-slate-50 to-gray-50",
    border: "border-slate-200",
    text: "text-slate-700",
    ring: "ring-slate-300",
    hover: "hover:from-slate-100 hover:to-gray-100",
  },
  {
    gradient: "from-fuchsia-500 to-purple-500",
    bg: "bg-gradient-to-r from-fuchsia-50 to-purple-50",
    border: "border-fuchsia-200",
    text: "text-fuchsia-700",
    ring: "ring-fuchsia-300",
    hover: "hover:from-fuchsia-100 hover:to-purple-100",
  },
  {
    gradient: "from-cyan-500 to-sky-500",
    bg: "bg-gradient-to-r from-cyan-50 to-sky-50",
    border: "border-cyan-200",
    text: "text-cyan-700",
    ring: "ring-cyan-300",
    hover: "hover:from-cyan-100 hover:to-sky-100",
  },
  {
    gradient: "from-teal-500 to-emerald-500",
    bg: "bg-gradient-to-r from-teal-50 to-emerald-50",
    border: "border-teal-200",
    text: "text-teal-700",
    ring: "ring-teal-300",
    hover: "hover:from-teal-100 hover:to-emerald-100",
  },
  {
    gradient: "from-lime-500 to-green-500",
    bg: "bg-gradient-to-r from-lime-50 to-green-50",
    border: "border-lime-200",
    text: "text-lime-700",
    ring: "ring-lime-300",
    hover: "hover:from-lime-100 hover:to-green-100",
  },
  {
    gradient: "from-yellow-500 to-amber-500",
    bg: "bg-gradient-to-r from-yellow-50 to-amber-50",
    border: "border-yellow-200",
    text: "text-yellow-700",
    ring: "ring-yellow-300",
    hover: "hover:from-yellow-100 hover:to-amber-100",
  },
  {
    gradient: "from-orange-500 to-red-500",
    bg: "bg-gradient-to-r from-orange-50 to-red-50",
    border: "border-orange-200",
    text: "text-orange-700",
    ring: "ring-orange-300",
    hover: "hover:from-orange-100 hover:to-red-100",
  },
  {
    gradient: "from-stone-500 to-zinc-500",
    bg: "bg-gradient-to-r from-stone-50 to-zinc-50",
    border: "border-stone-200",
    text: "text-stone-700",
    ring: "ring-stone-300",
    hover: "hover:from-stone-100 hover:to-zinc-100",
  },
  {
    gradient: "from-neutral-500 to-gray-500",
    bg: "bg-gradient-to-r from-neutral-50 to-gray-50",
    border: "border-neutral-200",
    text: "text-neutral-700",
    ring: "ring-neutral-300",
    hover: "hover:from-neutral-100 hover:to-gray-100",
  },
  {
    gradient: "from-violet-500 to-fuchsia-500",
    bg: "bg-gradient-to-r from-violet-50 to-fuchsia-50",
    border: "border-violet-200",
    text: "text-violet-700",
    ring: "ring-violet-300",
    hover: "hover:from-violet-100 hover:to-fuchsia-100",
  },
  {
    gradient: "from-indigo-500 to-blue-500",
    bg: "bg-gradient-to-r from-indigo-50 to-blue-50",
    border: "border-indigo-200",
    text: "text-indigo-700",
    ring: "ring-indigo-300",
    hover: "hover:from-indigo-100 hover:to-blue-100",
  },
  {
    gradient: "from-sky-500 to-cyan-500",
    bg: "bg-gradient-to-r from-sky-50 to-cyan-50",
    border: "border-sky-200",
    text: "text-sky-700",
    ring: "ring-sky-300",
    hover: "hover:from-sky-100 hover:to-cyan-100",
  },
  {
    gradient: "from-emerald-500 to-green-500",
    bg: "bg-gradient-to-r from-emerald-50 to-green-50",
    border: "border-emerald-200",
    text: "text-emerald-700",
    ring: "ring-emerald-300",
    hover: "hover:from-emerald-100 hover:to-green-100",
  },
  {
    gradient: "from-amber-500 to-yellow-500",
    bg: "bg-gradient-to-r from-amber-50 to-yellow-50",
    border: "border-amber-200",
    text: "text-amber-700",
    ring: "ring-amber-300",
    hover: "hover:from-amber-100 hover:to-yellow-100",
  },
  {
    gradient: "from-teal-500 to-cyan-500",
    bg: "bg-gradient-to-r from-teal-50 to-cyan-50",
    border: "border-teal-200",
    text: "text-teal-700",
    ring: "ring-teal-300",
    hover: "hover:from-teal-100 hover:to-cyan-100",
  },
  {
    gradient: "from-zinc-500 to-stone-500",
    bg: "bg-gradient-to-r from-zinc-50 to-stone-50",
    border: "border-zinc-200",
    text: "text-zinc-700",
    ring: "ring-zinc-300",
    hover: "hover:from-zinc-100 hover:to-stone-100",
  },
  {
    gradient: "from-gray-500 to-neutral-500",
    bg: "bg-gradient-to-r from-gray-50 to-neutral-50",
    border: "border-gray-200",
    text: "text-gray-700",
    ring: "ring-gray-300",
    hover: "hover:from-gray-100 hover:to-neutral-100",
  },
  {
    gradient: "from-pink-500 to-rose-500",
    bg: "bg-gradient-to-r from-pink-50 to-rose-50",
    border: "border-pink-200",
    text: "text-pink-700",
    ring: "ring-pink-300",
    hover: "hover:from-pink-100 hover:to-rose-100",
  },
  {
    gradient: "from-purple-500 to-indigo-500",
    bg: "bg-gradient-to-r from-purple-50 to-indigo-50",
    border: "border-purple-200",
    text: "text-purple-700",
    ring: "ring-purple-300",
    hover: "hover:from-purple-100 hover:to-indigo-100",
  },
  {
    gradient: "from-blue-500 to-indigo-500",
    bg: "bg-gradient-to-r from-blue-50 to-indigo-50",
    border: "border-blue-200",
    text: "text-blue-700",
    ring: "ring-blue-300",
    hover: "hover:from-blue-100 hover:to-indigo-100",
  },
  {
    gradient: "from-green-500 to-emerald-500",
    bg: "bg-gradient-to-r from-green-50 to-emerald-50",
    border: "border-green-200",
    text: "text-green-700",
    ring: "ring-green-300",
    hover: "hover:from-green-100 hover:to-emerald-100",
  },
  {
    gradient: "from-rose-500 to-fuchsia-500",
    bg: "bg-gradient-to-r from-rose-50 to-fuchsia-50",
    border: "border-rose-200",
    text: "text-rose-700",
    ring: "ring-rose-300",
    hover: "hover:from-rose-100 hover:to-fuchsia-100",
  },
  {
    gradient: "from-cyan-500 to-teal-500",
    bg: "bg-gradient-to-r from-cyan-50 to-teal-50",
    border: "border-cyan-200",
    text: "text-cyan-700",
    ring: "ring-cyan-300",
    hover: "hover:from-cyan-100 hover:to-teal-100",
  },
];
export const AUTO_SAVE_INTERVAL = 5 * 60 * 1000; // 5 minutes